# 应用服务 WEB 访问端口
server:
  port: 8081

# 应用名称
spring:
  application:
    name: spaceobj-advertise
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/spaceobj?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6380
    password:
  cloud:
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
    # Nacos认证信息
    nacos:
      discovery:
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: localhost:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public



