# 断路器的超时时间需要大于Ribbon的超时时间，不然不会触发重试。
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
ribbon:
  # 请求连接超时时间
  ConnectTimeout: 150000
  # 请求处理的超时时间
  ReadTimeout: 150000
  # 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  # 对当前实例的重试次数
  maxAutoRetries: 3
  # 切换实例的重试次数
#  MaxAutoRetriesNextServer: 2
